server:
  port: 8081
#\u6570\u636E\u6E90\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/conference?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: org.apache.commons.dbcp2.BasicDataSource  #\u8FDE\u63A5\u6C60\u7684\u914D\u7F6E
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      max-idle: 20
    driver-class-name: com.mysql.jdbc.Driver
#mapper\u6620\u5C04\u6587\u4EF6\u7684\u4F4D\u7F6E
mybatis:
  mapper-locations: classpath:mapper/*.xml

